version: "3.7"
services:
  watcher:
    build: ./package_sender
    network_mode: "host"
    restart: always
    env_file:
      - ./package_sender/.env
  mongo:
    image: mongo:4.4
    networks:
      - acheronet
    restart: unless-stopped

  caronte:
    image: ghcr.io/eciavatta/caronte:latest
    ports:
      - "3333:3333"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongo
    networks:
      - acheronet
    restart: unless-stopped

networks:
  acheronet:
